### ISSUE TITLE
Typo in go commands

### ISSUE THREAD

**Issue by kumaranvpl** [Ayiga/go-kit-middlewarer#3]
Typo in following command
`go get github.com/ayiga/go-middle-warer && \ go install github.com/ayiga/go-middle-warer`
It should be 
`go get github.com/ayiga/go-kit-middlewarer && \ go install github.com/ayiga/go-kit-middlewarer`

**Comment by Ayiga** [comment]
Oh gee, I didn't notice this, thanks for the heads up, this should now be fixed as of commit [f933f3a4](https://github.com/Ayiga/go-kit-middlewarer/commit/f933f3a4eb087078a89ec4ed0e3938bc9f367518)
